# Generated by Django 4.2.3 on 2023-08-22 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=150)),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('button_text', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ajouter un banner au centre de la page Home',
                'verbose_name_plural': 'Ajouter des banners au centre de la page Home',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Question & Answer',
                'verbose_name_plural': 'Questions & Answers',
            },
        ),
        migrations.CreateModel(
            name='Matacor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('ccp', models.CharField(max_length=50)),
                ('name_owner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Matacor information ',
                'verbose_name_plural': 'Matacor informations (ccp/email,tel...)',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'NewsLetter Email',
                'verbose_name_plural': 'NewsLetter Emails',
            },
        ),
        migrations.CreateModel(
            name='ShopHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_header_image', models.ImageField(upload_to='shop_imgs')),
                ('main_title', models.CharField(max_length=50)),
                ('second_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ajouter un categorie relie à des produit', 'verbose_name_plural': 'Ajouter des categories relie à des produit'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Ajouter Un coupon pour un produit', 'verbose_name_plural': 'Ajouter Un coupon pour un produit'},
        ),
        migrations.AlterModelOptions(
            name='excelfile',
            options={'verbose_name': "Ajouter des Produits à partir d'un fichier excel", 'verbose_name_plural': "Ajouter des Produits à partir d'un fichier excel"},
        ),
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'Ajouter Image de Produit', 'verbose_name_plural': 'Ajouter Images des Produits'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Ajouter Produit', 'verbose_name_plural': 'Ajouter Produits'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'la Commande confirmée', 'verbose_name_plural': 'les Commandes confirmées'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'la Commande dans un panier', 'verbose_name_plural': 'les Commandes dans les paniers non confirmée'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Ajouter un Slide avec text et lien', 'verbose_name_plural': 'Ajouter des Slides avec texts et liens'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('M-F', 'MALE-FEMALE'), ('E', 'ENFANTS')], default='M', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 19, 27, 46, 421938)),
        ),
        migrations.AddField(
            model_name='item',
            name='id_item',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='commun_ship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='recui_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='orders_recu/'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='wilaya_ship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.CharField(default="{'color':''}", max_length=1500),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Meilleur vente'), ('N', 'Nouveau'), ('P', 'Promotion')], max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'utilisateur avec sa wishlists',
                'verbose_name_plural': 'utilisateurs avec leurs wishlists',
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=190)),
                ('items', models.ManyToManyField(to='core.category')),
            ],
            options={
                'verbose_name': 'Ajouter un category ex(Vettements,collections..)',
                'verbose_name_plural': 'Ajouter un category ex(Vettements,collections..)',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/static/images/default-avatar.jpg', upload_to='user_profiles')),
                ('fullname', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=250)),
                ('adresse', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_upload_product/')),
                ('excel_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excelfile')),
            ],
            options={
                'verbose_name': "pour l'upload des mutiples images visite /images/upload/",
                'verbose_name_plural': "pour l'upload des mutiples images visite /images/upload/",
            },
        ),
        migrations.CreateModel(
            name='GenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=190)),
                ('categories', models.ManyToManyField(to='core.topcategory')),
            ],
            options={
                'verbose_name': 'Ajouter Gender category ex(hommes,femmes..)',
                'verbose_name_plural': 'Ajouter Gender category ex(hommes,femmes..)',
            },
        ),
        migrations.CreateModel(
            name='Comments_and_Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images_comments')),
                ('rating', models.FloatField(max_length=1)),
                ('comment', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 19, 27, 46, 432070))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commentaire de chaque produit',
                'verbose_name_plural': 'commentaires de chaque produit',
            },
        ),
        migrations.CreateModel(
            name='Comment_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images_comments')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comments_and_ratings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image de commentaire',
                'verbose_name_plural': 'les images des commentaires',
            },
        ),
        migrations.CreateModel(
            name='Banner_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banner_imgs')),
                ('banner_link', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topcategory')),
            ],
            options={
                'verbose_name': 'Ajouter un banner image pour un category ex(vettements, collection)',
                'verbose_name_plural': 'Ajouter un banner image pour un category  ex(vettements, collection)',
            },
        ),
    ]
