# Generated by Django 4.2.3 on 2023-08-22 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_essential_faq_matacor_info_newsletteremails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 19, 41, 36, 40167)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 19, 41, 36, 40167)),
        ),
    ]
