# Generated by Django 4.2.3 on 2023-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_recui_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='commun_ship',
            field=models.CharField(default='dd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='ds', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(default='ff', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='wilaya_ship',
            field=models.CharField(default='ff', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
