# Generated by Django 4.2.3 on 2023-08-06 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_essential_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_header_image', models.ImageField(upload_to='shop_imgs')),
                ('main_title', models.CharField(max_length=50)),
                ('second_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 4, 20, 39, 873016)),
        ),
    ]
