# Generated by Django 4.2.3 on 2023-08-06 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopheader_alter_item_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matacor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ImageField(upload_to='shop_imgs')),
                ('phone_number', models.CharField(max_length=50)),
                ('ccp', models.CharField(max_length=50)),
                ('name_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 5, 50, 46, 357654)),
        ),
    ]
