# Generated by Django 4.2.3 on 2023-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_billing_address_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='XS', max_length=5),
            preserve_default=False,
        ),
    ]
