# Generated by Django 4.2.3 on 2023-08-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_matacor_info_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idxn',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 15, 4, 22, 414514)),
        ),
        migrations.AlterField(
            model_name='order',
            name='recui_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='orders_recu/'),
        ),
    ]
