# Generated by Django 4.2.3 on 2023-08-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_essential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='price',
            field=models.IntegerField(),
        ),
    ]
