# Generated by Django 4.2.3 on 2023-08-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_idxn_alter_item_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='idxn',
            new_name='id_item',
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 15, 4, 42, 178013)),
        ),
    ]
