# Generated by Django 4.2.3 on 2023-08-06 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_idxn_item_id_item_alter_item_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileWithImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='excel_files/')),
                ('images', models.ImageField(upload_to='products_items/')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 16, 29, 6, 349784)),
        ),
    ]
