# Generated by Django 4.2.3 on 2023-08-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_essential_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='model_type',
            field=models.CharField(default='homewear', max_length=150),
            preserve_default=False,
        ),
    ]
