# Generated by Django 4.2.3 on 2023-08-26 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='label',
            field=models.CharField(choices=[('A', 'ajouter'), ('M', 'modifier')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 15, 37, 56, 389369)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 15, 37, 56, 382863)),
        ),
    ]
