# Generated by Django 4.2.3 on 2023-07-21 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=5.0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist_num',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
