# Generated by Django 4.2.3 on 2023-08-28 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_excelfile_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_ar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 12, 29, 18, 3782)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 12, 29, 17, 988162)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.CharField(default="{'color':''}", max_length=5500),
        ),
    ]
