# Generated by Django 4.2.3 on 2023-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_rating_item_wishlist_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='opinion_num',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
