# Generated by Django 4.2.3 on 2023-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_topcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcategory',
            name='slug',
            field=models.SlugField(default='dsd', max_length=190, unique=True),
            preserve_default=False,
        ),
    ]
