# Generated by Django 4.2.3 on 2023-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_opinion_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='has_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
