# Generated by Django 4.2.3 on 2023-08-07 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 16, 56, 52, 761118)),
        ),
        migrations.AlterField(
            model_name='matacor_info',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
