# Generated by Django 4.2.3 on 2023-08-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_topcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('categories', models.ManyToManyField(to='core.topcategory')),
            ],
        ),
    ]
