# Generated by Django 4.2.3 on 2023-08-08 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_date_added_alter_matacor_info_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 15, 33, 13, 156161)),
        ),
    ]
