# Generated by Django 4.2.3 on 2023-07-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_coupon_code_item_has_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
