# Generated by Django 4.2.3 on 2023-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_price_after_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='show_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
