# Generated by Django 4.2.3 on 2023-08-08 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_images_upload_alter_item_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('M-F', 'MALE-FEMALE'), ('E', 'ENFANTS')], default='M', max_length=3),
        ),
        migrations.AlterField(
            model_name='images_upload',
            name='images',
            field=models.ImageField(upload_to='images_upload_product/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 21, 19, 51, 209721)),
        ),
    ]
