# Generated by Django 4.2.3 on 2023-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendercategory',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recui_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='orders_recu/'),
        ),
    ]
