# Generated by Django 4.2.3 on 2023-08-08 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_excelfile_gender_alter_images_upload_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 21, 39, 5, 293440)),
        ),
    ]
