# Generated by Django 4.2.3 on 2023-09-26 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 12, 29, 26, 75704)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 12, 29, 26, 66164)),
        ),
    ]
