# Generated by Django 4.2.3 on 2023-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_show_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Shipping',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
