# Generated by Django 4.2.3 on 2023-08-09 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 46, 24, 639373)),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=1),
        ),
    ]
