# Generated by Django 4.2.3 on 2023-08-10 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_essential_price_alter_item_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 6, 52, 13, 141719)),
        ),
    ]
