# Generated by Django 4.2.3 on 2023-07-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images1/'),
        ),
    ]
