# Generated by Django 4.2.3 on 2023-09-26 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image_mob',
            field=models.ImageField(default=1, help_text='Size:  ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 19, 15, 7, 534943)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 19, 15, 7, 520574)),
        ),
    ]
