# Generated by Django 4.2.3 on 2023-08-10 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item_brand_name_alter_item_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_upload',
            name='title',
        ),
        migrations.AddField(
            model_name='images_upload',
            name='excel_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.excelfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 11, 27, 30, 434141)),
        ),
    ]
