# Generated by Django 4.2.3 on 2023-07-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postimageslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_item')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimageslist',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
