# Generated by Django 4.2.3 on 2023-08-10 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_images_upload_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 11, 28, 11, 149505)),
        ),
    ]
