# Generated by Django 4.2.3 on 2023-09-30 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_slide_image_mob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matacor_info',
            name='contact_footer',
            field=models.TextField(default='Des questions? Faites-nous savoir en nous envoyant une requête par e-mail ou contactez-nous par téléphone ou à Eurl AllDesigns ain-naadja , algeries, Algeria', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 21, 31, 29, 303927)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 21, 31, 29, 292984)),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Meilleur vente'), ('N', 'Nouveau'), ('P', 'Promo')], max_length=1),
        ),
    ]
