# Generated by Django 4.2.3 on 2023-10-16 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_banner_category_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 9, 18, 28, 758279)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 9, 18, 28, 746897)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderidpai',
            field=models.CharField(default='', max_length=200),
        ),
    ]
