# Generated by Django 4.2.3 on 2023-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_imageitem_remove_postimage_post_remove_item_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
