# Generated by Django 4.2.3 on 2023-08-18 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_item_date_added_comments_and_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Ajouter Produit', 'verbose_name_plural': 'Ajouter Produits'},
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 2, 29, 33, 398101)),
        ),
    ]
