# Generated by Django 4.2.3 on 2023-10-16 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderidpai',
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 12, 22, 9, 19945)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 12, 22, 9, 9330)),
        ),
    ]
