# Generated by Django 4.2.3 on 2023-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='color_exist',
        ),
        migrations.AddField(
            model_name='item',
            name='color_not_exist',
            field=models.CharField(default='red,red', max_length=250),
            preserve_default=False,
        ),
    ]
