# Generated by Django 4.2.3 on 2023-08-18 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_item_options_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner_category',
            options={'verbose_name': 'Ajouter un banner image pour un category ex(vettements, collection)', 'verbose_name_plural': 'Ajouter un banner image pour un category  ex(vettements, collection)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ajouter un categorie relie à des produit', 'verbose_name_plural': 'Ajouter des categories relie à des produit'},
        ),
        migrations.AlterModelOptions(
            name='comments_and_ratings',
            options={'verbose_name': 'commentaire de chaque produit', 'verbose_name_plural': 'commentaires de chaque produit'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Ajouter Un coupon pour un produit', 'verbose_name_plural': 'Ajouter Un coupon pour un produit'},
        ),
        migrations.AlterModelOptions(
            name='essential',
            options={'verbose_name': 'Ajouter un banner au centre de la page Home', 'verbose_name_plural': 'Ajouter des banners au centre de la page Home'},
        ),
        migrations.AlterModelOptions(
            name='excelfile',
            options={'verbose_name': "Ajouter des Produits à partir d'un fichier excel", 'verbose_name_plural': "Ajouter des Produits à partir d'un fichier excel"},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Question & Answer', 'verbose_name_plural': 'Questions & Answers'},
        ),
        migrations.AlterModelOptions(
            name='gendercategory',
            options={'verbose_name': 'Ajouter Gender category ex(hommes,femmes..)', 'verbose_name_plural': 'Ajouter Gender category ex(hommes,femmes..)'},
        ),
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'Image de Produit', 'verbose_name_plural': 'Images des Produits'},
        ),
        migrations.AlterModelOptions(
            name='images_upload',
            options={'verbose_name': "pour l'upload des images visite /images/upload/", 'verbose_name_plural': "pour l'upload des images visite /images/upload/"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'la Commande confirmée', 'verbose_name_plural': 'les Commandes confirmées'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'la Commande dans un panier', 'verbose_name_plural': 'les Commandes dans les paniers'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Ajouter un Slide avec text et lien', 'verbose_name_plural': 'Ajouter des Slides avec texts et liens'},
        ),
        migrations.AlterModelOptions(
            name='topcategory',
            options={'verbose_name': 'Ajouter un category ex(Vettements,collections..)', 'verbose_name_plural': 'Ajouter un category ex(Vettements,collections..)'},
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 2, 47, 26, 338796)),
        ),
    ]
