# Generated by Django 4.2.3 on 2023-08-19 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_banner_category_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'Ajouter Image de Produit', 'verbose_name_plural': 'Ajouter Images des Produits'},
        ),
        migrations.AlterModelOptions(
            name='images_upload',
            options={'verbose_name': "pour l'upload des mutiples images visite /images/upload/", 'verbose_name_plural': "pour l'upload des mutiples images visite /images/upload/"},
        ),
        migrations.AlterModelOptions(
            name='matacor_info',
            options={'verbose_name': 'Matacor information ', 'verbose_name_plural': 'Matacor informations (ccp/email,tel...)'},
        ),
        migrations.AlterModelOptions(
            name='newsletteremails',
            options={'verbose_name': 'NewsLetter Email', 'verbose_name_plural': 'NewsLetter Emails'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'la Commande dans un panier', 'verbose_name_plural': 'les Commandes dans les paniers non confirmée'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'utilisateur avec sa wishlists', 'verbose_name_plural': 'utilisateurs avec leurs wishlists'},
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 19, 56, 23, 315163)),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.CharField(default="{'color':''}", max_length=1500),
        ),
    ]
