# Generated by Django 4.2.3 on 2023-10-18 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_order_orderidpai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardholderName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='depositAmount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 5, 41, 41, 665365)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 5, 41, 41, 654531)),
        ),
    ]
