# Generated by Django 4.2.3 on 2023-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_color_item_color_exist_item_color_not_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_exist',
            field=models.CharField(default='M', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size_not_exist',
            field=models.CharField(default='M', max_length=250),
            preserve_default=False,
        ),
    ]
