# Generated by Django 4.2.3 on 2023-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_item_size_exist_item_size_not_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color_exist',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_not_exist',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='size_exist',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='size_not_exist',
            field=models.CharField(default='', max_length=250),
        ),
    ]
