# Generated by Django 4.2.3 on 2023-10-18 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_paiement_meth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pai_meth_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 6, 19, 42, 333841)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 6, 19, 42, 321320)),
        ),
        migrations.AlterField(
            model_name='order',
            name='paiement_meth',
            field=models.CharField(choices=[('E', 'E-paiement'), ('C', 'Reçu de Paiement')], max_length=1),
        ),
    ]
