# Generated by Django 4.2.3 on 2023-10-18 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pai_meth_1',
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 6, 53, 49, 638729)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 6, 53, 49, 628853)),
        ),
    ]
