# Generated by Django 4.2.3 on 2023-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_item_color_exist_alter_item_color_not_exist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.TextField(default='clothes'),
            preserve_default=False,
        ),
    ]
