# Generated by Django 4.2.3 on 2023-10-26 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_order_pai_meth_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'les produits dans un panier', 'verbose_name_plural': 'les Produits dans les paniers'},
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 0, 35, 983231)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 0, 35, 970373)),
        ),
        migrations.AlterField(
            model_name='order',
            name='cardholderName',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
