# Generated by Django 4.2.3 on 2023-11-11 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ad_homepage_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=590, unique=True),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 0, 49, 23, 392798)),
        ),
        migrations.AlterField(
            model_name='gendercategory',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='slug',
            field=models.SlugField(max_length=590),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 0, 49, 23, 382717)),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=590, unique=True),
        ),
        migrations.AlterField(
            model_name='topcategory',
            name='slug',
            field=models.CharField(max_length=590),
        ),
        migrations.AlterField(
            model_name='topcategory',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
