# Generated by Django 4.2.3 on 2023-07-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_imageitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
    ]
