# Generated by Django 4.2.3 on 2023-11-11 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 2, 24, 2, 149096)),
        ),
        migrations.AlterField(
            model_name='item',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 2, 24, 2, 134544)),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.CharField(default="{'color':''}", max_length=5500),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
