# Generated by Django 5.0 on 2023-12-13 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_order_formurl_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approvalCode',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 14, 50, 46, 321679)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 14, 50, 46, 303817)),
        ),
    ]
