# Generated by Django 4.2.3 on 2023-07-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
