# Generated by Django 4.2.3 on 2023-07-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_imageitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='slug',
        ),
    ]
