# Generated by Django 4.2.3 on 2023-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_imageitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='slug',
            field=models.SlugField(default='dd-djh', unique=True),
            preserve_default=False,
        ),
    ]
