# Generated by Django 4.2.3 on 2023-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_imageitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='slug',
            field=models.SlugField(),
        ),
    ]
