# Generated by Django 5.0 on 2023-12-26 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_order_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 21, 59, 28, 390780)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 21, 59, 28, 371077)),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.JSONField(),
        ),
    ]
