# Generated by Django 4.2.3 on 2023-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_imageitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(default="{'color':'black'}", max_length=1500),
        ),
    ]
