# Generated by Django 4.2.3 on 2023-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
