# Generated by Django 4.2.3 on 2023-07-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_item_description_short_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='article_id',
            field=models.CharField(default='TPRSS22TU0070', max_length=50),
            preserve_default=False,
        ),
    ]
