# Generated by Django 5.0 on 2024-01-11 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 18, 19, 21, 129278)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 18, 19, 21, 111054)),
        ),
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
