# Generated by Django 4.2.3 on 2023-07-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_item_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('M-F', 'MALE-FEMALE'), ('E', 'ENFANTS')], default='M', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='size_exist',
            field=models.CharField(blank=True, default='34,36,38,40,42', max_length=250, null=True),
        ),
    ]
