# Generated by Django 5.0 on 2024-01-11 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_comments_and_ratings_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcategory',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('M-F', 'MALE-FEMALE'), ('E', 'ENFANTS')], default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 18, 21, 16, 210733)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 18, 21, 16, 192829)),
        ),
    ]
