# Generated by Django 5.0 on 2024-01-11 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_topcategory_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_category',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('M-F', 'MALE-FEMALE'), ('E', 'ENFANTS')], default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='comments_and_ratings',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 18, 56, 14, 640929)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 18, 56, 14, 621544)),
        ),
    ]
